name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      test1: 123
    steps:
      - id: set-matrix
        run: "echo ${test1}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: "echo ${needs.job1.outputs.test1}"
